//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VDMMutiline.APIExport.MonthSearch {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlightFareInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FlightFareInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private System.Nullable<System.DateTime> StartDateField;
        
        private System.Nullable<System.DateTime> EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartPointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndPointField;
        
        private System.Nullable<int> StopsField;
        
        private System.Nullable<int> DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SelectValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        private System.Nullable<int> AdultField;
        
        private System.Nullable<int> ChildField;
        
        private System.Nullable<int> InfantField;
        
        private System.Nullable<double> PriceAdultField;
        
        private System.Nullable<double> PriceChildField;
        
        private System.Nullable<double> PriceInfantField;
        
        private System.Nullable<double> FeeAdultField;
        
        private System.Nullable<double> FeeChildField;
        
        private System.Nullable<double> FeeInfantField;
        
        private System.Nullable<double> TaxAdultField;
        
        private System.Nullable<double> TaxChildField;
        
        private System.Nullable<double> TaxInfantField;
        
        private System.Nullable<double> TotalPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FareClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FltNumbField;
        
        private System.Nullable<bool> PromoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AirlineCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DebugIDField;
        
        private System.Nullable<int> ItineraryTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionAllField;
        
        private System.Nullable<double> PriceBeforField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VDMMutiline.APIExport.MonthSearch.AvailFlight[] AvailFlightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string StartPoint {
            get {
                return this.StartPointField;
            }
            set {
                if ((object.ReferenceEquals(this.StartPointField, value) != true)) {
                    this.StartPointField = value;
                    this.RaisePropertyChanged("StartPoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string EndPoint {
            get {
                return this.EndPointField;
            }
            set {
                if ((object.ReferenceEquals(this.EndPointField, value) != true)) {
                    this.EndPointField = value;
                    this.RaisePropertyChanged("EndPoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> Stops {
            get {
                return this.StopsField;
            }
            set {
                if ((this.StopsField.Equals(value) != true)) {
                    this.StopsField = value;
                    this.RaisePropertyChanged("Stops");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string SelectValue {
            get {
                return this.SelectValueField;
            }
            set {
                if ((object.ReferenceEquals(this.SelectValueField, value) != true)) {
                    this.SelectValueField = value;
                    this.RaisePropertyChanged("SelectValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<int> Adult {
            get {
                return this.AdultField;
            }
            set {
                if ((this.AdultField.Equals(value) != true)) {
                    this.AdultField = value;
                    this.RaisePropertyChanged("Adult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<int> Child {
            get {
                return this.ChildField;
            }
            set {
                if ((this.ChildField.Equals(value) != true)) {
                    this.ChildField = value;
                    this.RaisePropertyChanged("Child");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.Nullable<int> Infant {
            get {
                return this.InfantField;
            }
            set {
                if ((this.InfantField.Equals(value) != true)) {
                    this.InfantField = value;
                    this.RaisePropertyChanged("Infant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.Nullable<double> PriceAdult {
            get {
                return this.PriceAdultField;
            }
            set {
                if ((this.PriceAdultField.Equals(value) != true)) {
                    this.PriceAdultField = value;
                    this.RaisePropertyChanged("PriceAdult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public System.Nullable<double> PriceChild {
            get {
                return this.PriceChildField;
            }
            set {
                if ((this.PriceChildField.Equals(value) != true)) {
                    this.PriceChildField = value;
                    this.RaisePropertyChanged("PriceChild");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public System.Nullable<double> PriceInfant {
            get {
                return this.PriceInfantField;
            }
            set {
                if ((this.PriceInfantField.Equals(value) != true)) {
                    this.PriceInfantField = value;
                    this.RaisePropertyChanged("PriceInfant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public System.Nullable<double> FeeAdult {
            get {
                return this.FeeAdultField;
            }
            set {
                if ((this.FeeAdultField.Equals(value) != true)) {
                    this.FeeAdultField = value;
                    this.RaisePropertyChanged("FeeAdult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public System.Nullable<double> FeeChild {
            get {
                return this.FeeChildField;
            }
            set {
                if ((this.FeeChildField.Equals(value) != true)) {
                    this.FeeChildField = value;
                    this.RaisePropertyChanged("FeeChild");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public System.Nullable<double> FeeInfant {
            get {
                return this.FeeInfantField;
            }
            set {
                if ((this.FeeInfantField.Equals(value) != true)) {
                    this.FeeInfantField = value;
                    this.RaisePropertyChanged("FeeInfant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public System.Nullable<double> TaxAdult {
            get {
                return this.TaxAdultField;
            }
            set {
                if ((this.TaxAdultField.Equals(value) != true)) {
                    this.TaxAdultField = value;
                    this.RaisePropertyChanged("TaxAdult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public System.Nullable<double> TaxChild {
            get {
                return this.TaxChildField;
            }
            set {
                if ((this.TaxChildField.Equals(value) != true)) {
                    this.TaxChildField = value;
                    this.RaisePropertyChanged("TaxChild");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public System.Nullable<double> TaxInfant {
            get {
                return this.TaxInfantField;
            }
            set {
                if ((this.TaxInfantField.Equals(value) != true)) {
                    this.TaxInfantField = value;
                    this.RaisePropertyChanged("TaxInfant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public System.Nullable<double> TotalPrice {
            get {
                return this.TotalPriceField;
            }
            set {
                if ((this.TotalPriceField.Equals(value) != true)) {
                    this.TotalPriceField = value;
                    this.RaisePropertyChanged("TotalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string GroupClass {
            get {
                return this.GroupClassField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupClassField, value) != true)) {
                    this.GroupClassField = value;
                    this.RaisePropertyChanged("GroupClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string FareClass {
            get {
                return this.FareClassField;
            }
            set {
                if ((object.ReferenceEquals(this.FareClassField, value) != true)) {
                    this.FareClassField = value;
                    this.RaisePropertyChanged("FareClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string FltNumb {
            get {
                return this.FltNumbField;
            }
            set {
                if ((object.ReferenceEquals(this.FltNumbField, value) != true)) {
                    this.FltNumbField = value;
                    this.RaisePropertyChanged("FltNumb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=25)]
        public System.Nullable<bool> Promo {
            get {
                return this.PromoField;
            }
            set {
                if ((this.PromoField.Equals(value) != true)) {
                    this.PromoField = value;
                    this.RaisePropertyChanged("Promo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string AirlineCode {
            get {
                return this.AirlineCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AirlineCodeField, value) != true)) {
                    this.AirlineCodeField = value;
                    this.RaisePropertyChanged("AirlineCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string DebugID {
            get {
                return this.DebugIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DebugIDField, value) != true)) {
                    this.DebugIDField = value;
                    this.RaisePropertyChanged("DebugID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=28)]
        public System.Nullable<int> ItineraryType {
            get {
                return this.ItineraryTypeField;
            }
            set {
                if ((this.ItineraryTypeField.Equals(value) != true)) {
                    this.ItineraryTypeField = value;
                    this.RaisePropertyChanged("ItineraryType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string SessionAll {
            get {
                return this.SessionAllField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionAllField, value) != true)) {
                    this.SessionAllField = value;
                    this.RaisePropertyChanged("SessionAll");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=30)]
        public System.Nullable<double> PriceBefor {
            get {
                return this.PriceBeforField;
            }
            set {
                if ((this.PriceBeforField.Equals(value) != true)) {
                    this.PriceBeforField = value;
                    this.RaisePropertyChanged("PriceBefor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public VDMMutiline.APIExport.MonthSearch.AvailFlight[] AvailFlight {
            get {
                return this.AvailFlightField;
            }
            set {
                if ((object.ReferenceEquals(this.AvailFlightField, value) != true)) {
                    this.AvailFlightField = value;
                    this.RaisePropertyChanged("AvailFlight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvailFlight", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AvailFlight : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> IdField;
        
        private System.Nullable<int> Id_veField;
        
        private System.Nullable<System.DateTime> StartDateField;
        
        private System.Nullable<System.DateTime> EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartPointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndPointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlightNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassField;
        
        private System.Nullable<int> DurationField;
        
        private System.Nullable<int> PartField;
        
        private System.Nullable<int> SeatsRemainingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> Id_ve {
            get {
                return this.Id_veField;
            }
            set {
                if ((this.Id_veField.Equals(value) != true)) {
                    this.Id_veField = value;
                    this.RaisePropertyChanged("Id_ve");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string StartPoint {
            get {
                return this.StartPointField;
            }
            set {
                if ((object.ReferenceEquals(this.StartPointField, value) != true)) {
                    this.StartPointField = value;
                    this.RaisePropertyChanged("StartPoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string EndPoint {
            get {
                return this.EndPointField;
            }
            set {
                if ((object.ReferenceEquals(this.EndPointField, value) != true)) {
                    this.EndPointField = value;
                    this.RaisePropertyChanged("EndPoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string FlightNumber {
            get {
                return this.FlightNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.FlightNumberField, value) != true)) {
                    this.FlightNumberField = value;
                    this.RaisePropertyChanged("FlightNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Plane {
            get {
                return this.PlaneField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaneField, value) != true)) {
                    this.PlaneField = value;
                    this.RaisePropertyChanged("Plane");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Class {
            get {
                return this.ClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassField, value) != true)) {
                    this.ClassField = value;
                    this.RaisePropertyChanged("Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<int> Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<int> Part {
            get {
                return this.PartField;
            }
            set {
                if ((this.PartField.Equals(value) != true)) {
                    this.PartField = value;
                    this.RaisePropertyChanged("Part");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.Nullable<int> SeatsRemaining {
            get {
                return this.SeatsRemainingField;
            }
            set {
                if ((this.SeatsRemainingField.Equals(value) != true)) {
                    this.SeatsRemainingField = value;
                    this.RaisePropertyChanged("SeatsRemaining");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HanchesohieuInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class HanchesohieuInfo : VDMMutiline.APIExport.MonthSearch.tbl_Hanchesohieu {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HangbayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HangveField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Hangbay {
            get {
                return this.HangbayField;
            }
            set {
                if ((object.ReferenceEquals(this.HangbayField, value) != true)) {
                    this.HangbayField = value;
                    this.RaisePropertyChanged("Hangbay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Hangve {
            get {
                return this.HangveField;
            }
            set {
                if ((object.ReferenceEquals(this.HangveField, value) != true)) {
                    this.HangveField = value;
                    this.RaisePropertyChanged("Hangve");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_Hanchesohieu", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VDMMutiline.APIExport.MonthSearch.HanchesohieuInfo))]
    public partial class tbl_Hanchesohieu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private System.Nullable<int> IdhangBayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SohieuHancheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartPoindField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndPoindField;
        
        private System.Nullable<double> PricedField;
        
        private System.Nullable<bool> ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VDMMutiline.APIExport.MonthSearch.tbl_hangbay tbl_hangbayField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> IdhangBay {
            get {
                return this.IdhangBayField;
            }
            set {
                if ((this.IdhangBayField.Equals(value) != true)) {
                    this.IdhangBayField = value;
                    this.RaisePropertyChanged("IdhangBay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SohieuHanche {
            get {
                return this.SohieuHancheField;
            }
            set {
                if ((object.ReferenceEquals(this.SohieuHancheField, value) != true)) {
                    this.SohieuHancheField = value;
                    this.RaisePropertyChanged("SohieuHanche");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StartPoind {
            get {
                return this.StartPoindField;
            }
            set {
                if ((object.ReferenceEquals(this.StartPoindField, value) != true)) {
                    this.StartPoindField = value;
                    this.RaisePropertyChanged("StartPoind");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string EndPoind {
            get {
                return this.EndPoindField;
            }
            set {
                if ((object.ReferenceEquals(this.EndPoindField, value) != true)) {
                    this.EndPoindField = value;
                    this.RaisePropertyChanged("EndPoind");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<double> Priced {
            get {
                return this.PricedField;
            }
            set {
                if ((this.PricedField.Equals(value) != true)) {
                    this.PricedField = value;
                    this.RaisePropertyChanged("Priced");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<bool> Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public VDMMutiline.APIExport.MonthSearch.tbl_hangbay tbl_hangbay {
            get {
                return this.tbl_hangbayField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_hangbayField, value) != true)) {
                    this.tbl_hangbayField = value;
                    this.RaisePropertyChanged("tbl_hangbay");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_hangbay", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class tbl_hangbay : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeHangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HangVeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VDMMutiline.APIExport.MonthSearch.ArrayOfTbl_Hanchesohieu tbl_HanchesohieusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CodeHang {
            get {
                return this.CodeHangField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeHangField, value) != true)) {
                    this.CodeHangField = value;
                    this.RaisePropertyChanged("CodeHang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string HangVe {
            get {
                return this.HangVeField;
            }
            set {
                if ((object.ReferenceEquals(this.HangVeField, value) != true)) {
                    this.HangVeField = value;
                    this.RaisePropertyChanged("HangVe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public VDMMutiline.APIExport.MonthSearch.ArrayOfTbl_Hanchesohieu tbl_Hanchesohieus {
            get {
                return this.tbl_HanchesohieusField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_HanchesohieusField, value) != true)) {
                    this.tbl_HanchesohieusField = value;
                    this.RaisePropertyChanged("tbl_Hanchesohieus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfTbl_Hanchesohieu", Namespace="http://tempuri.org/", ItemName="tbl_Hanchesohieu")]
    [System.SerializableAttribute()]
    public class ArrayOfTbl_Hanchesohieu : System.Collections.Generic.List<VDMMutiline.APIExport.MonthSearch.tbl_Hanchesohieu> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_Cauhinhtaikhoan", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VDMMutiline.APIExport.MonthSearch.CauhinhtaikhoanInfo))]
    public partial class tbl_Cauhinhtaikhoan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdhangBayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassField;
        
        private System.Nullable<bool> KhoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VDMMutiline.APIExport.MonthSearch.ArrayOfTbl_ChiTietCauHinhTaiKhoan tbl_ChiTietCauHinhTaiKhoansField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IdhangBay {
            get {
                return this.IdhangBayField;
            }
            set {
                if ((object.ReferenceEquals(this.IdhangBayField, value) != true)) {
                    this.IdhangBayField = value;
                    this.RaisePropertyChanged("IdhangBay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Pass {
            get {
                return this.PassField;
            }
            set {
                if ((object.ReferenceEquals(this.PassField, value) != true)) {
                    this.PassField = value;
                    this.RaisePropertyChanged("Pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<bool> Khoa {
            get {
                return this.KhoaField;
            }
            set {
                if ((this.KhoaField.Equals(value) != true)) {
                    this.KhoaField = value;
                    this.RaisePropertyChanged("Khoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public VDMMutiline.APIExport.MonthSearch.ArrayOfTbl_ChiTietCauHinhTaiKhoan tbl_ChiTietCauHinhTaiKhoans {
            get {
                return this.tbl_ChiTietCauHinhTaiKhoansField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_ChiTietCauHinhTaiKhoansField, value) != true)) {
                    this.tbl_ChiTietCauHinhTaiKhoansField = value;
                    this.RaisePropertyChanged("tbl_ChiTietCauHinhTaiKhoans");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CauhinhtaikhoanInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CauhinhtaikhoanInfo : VDMMutiline.APIExport.MonthSearch.tbl_Cauhinhtaikhoan {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfTbl_ChiTietCauHinhTaiKhoan", Namespace="http://tempuri.org/", ItemName="tbl_ChiTietCauHinhTaiKhoan")]
    [System.SerializableAttribute()]
    public class ArrayOfTbl_ChiTietCauHinhTaiKhoan : System.Collections.Generic.List<VDMMutiline.APIExport.MonthSearch.tbl_ChiTietCauHinhTaiKhoan> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_ChiTietCauHinhTaiKhoan", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class tbl_ChiTietCauHinhTaiKhoan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private System.Nullable<int> IdCauhinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartPoindField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndpoindField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VDMMutiline.APIExport.MonthSearch.tbl_Cauhinhtaikhoan tbl_CauhinhtaikhoanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> IdCauhinh {
            get {
                return this.IdCauhinhField;
            }
            set {
                if ((this.IdCauhinhField.Equals(value) != true)) {
                    this.IdCauhinhField = value;
                    this.RaisePropertyChanged("IdCauhinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StartPoind {
            get {
                return this.StartPoindField;
            }
            set {
                if ((object.ReferenceEquals(this.StartPoindField, value) != true)) {
                    this.StartPoindField = value;
                    this.RaisePropertyChanged("StartPoind");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Endpoind {
            get {
                return this.EndpoindField;
            }
            set {
                if ((object.ReferenceEquals(this.EndpoindField, value) != true)) {
                    this.EndpoindField = value;
                    this.RaisePropertyChanged("Endpoind");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public VDMMutiline.APIExport.MonthSearch.tbl_Cauhinhtaikhoan tbl_Cauhinhtaikhoan {
            get {
                return this.tbl_CauhinhtaikhoanField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_CauhinhtaikhoanField, value) != true)) {
                    this.tbl_CauhinhtaikhoanField = value;
                    this.RaisePropertyChanged("tbl_Cauhinhtaikhoan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MonthSearch.MonthSearchSoap")]
    public interface MonthSearchSoap {
        
        // CODEGEN: Generating message contract since element name destinationAirportCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMonthlyTicket", ReplyAction="*")]
        VDMMutiline.APIExport.MonthSearch.GetMonthlyTicketResponse GetMonthlyTicket(VDMMutiline.APIExport.MonthSearch.GetMonthlyTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMonthlyTicket", ReplyAction="*")]
        System.Threading.Tasks.Task<VDMMutiline.APIExport.MonthSearch.GetMonthlyTicketResponse> GetMonthlyTicketAsync(VDMMutiline.APIExport.MonthSearch.GetMonthlyTicketRequest request);
        
        // CODEGEN: Generating message contract since element name destinationAirportCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFlightFareInfo", ReplyAction="*")]
        VDMMutiline.APIExport.MonthSearch.GetFlightFareInfoResponse GetFlightFareInfo(VDMMutiline.APIExport.MonthSearch.GetFlightFareInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFlightFareInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<VDMMutiline.APIExport.MonthSearch.GetFlightFareInfoResponse> GetFlightFareInfoAsync(VDMMutiline.APIExport.MonthSearch.GetFlightFareInfoRequest request);
        
        // CODEGEN: Generating message contract since element name hang from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Getlisthanche", ReplyAction="*")]
        VDMMutiline.APIExport.MonthSearch.GetlisthancheResponse Getlisthanche(VDMMutiline.APIExport.MonthSearch.GetlisthancheRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Getlisthanche", ReplyAction="*")]
        System.Threading.Tasks.Task<VDMMutiline.APIExport.MonthSearch.GetlisthancheResponse> GetlisthancheAsync(VDMMutiline.APIExport.MonthSearch.GetlisthancheRequest request);
        
        // CODEGEN: Generating message contract since element name hang from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetlisthancheAll", ReplyAction="*")]
        VDMMutiline.APIExport.MonthSearch.GetlisthancheAllResponse GetlisthancheAll(VDMMutiline.APIExport.MonthSearch.GetlisthancheAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetlisthancheAll", ReplyAction="*")]
        System.Threading.Tasks.Task<VDMMutiline.APIExport.MonthSearch.GetlisthancheAllResponse> GetlisthancheAllAsync(VDMMutiline.APIExport.MonthSearch.GetlisthancheAllRequest request);
        
        // CODEGEN: Generating message contract since element name hang from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetlistCauHinhTaiKhoan", ReplyAction="*")]
        VDMMutiline.APIExport.MonthSearch.GetlistCauHinhTaiKhoanResponse GetlistCauHinhTaiKhoan(VDMMutiline.APIExport.MonthSearch.GetlistCauHinhTaiKhoanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetlistCauHinhTaiKhoan", ReplyAction="*")]
        System.Threading.Tasks.Task<VDMMutiline.APIExport.MonthSearch.GetlistCauHinhTaiKhoanResponse> GetlistCauHinhTaiKhoanAsync(VDMMutiline.APIExport.MonthSearch.GetlistCauHinhTaiKhoanRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMonthlyTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMonthlyTicket", Namespace="http://tempuri.org/", Order=0)]
        public VDMMutiline.APIExport.MonthSearch.GetMonthlyTicketRequestBody Body;
        
        public GetMonthlyTicketRequest() {
        }
        
        public GetMonthlyTicketRequest(VDMMutiline.APIExport.MonthSearch.GetMonthlyTicketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMonthlyTicketRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int mountvalue;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int year;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string destinationAirportCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string departureAirportCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int adult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int children;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int infant;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string pass;
        
        public GetMonthlyTicketRequestBody() {
        }
        
        public GetMonthlyTicketRequestBody(int mountvalue, int year, string destinationAirportCode, string departureAirportCode, int adult, int children, int infant, string username, string pass) {
            this.mountvalue = mountvalue;
            this.year = year;
            this.destinationAirportCode = destinationAirportCode;
            this.departureAirportCode = departureAirportCode;
            this.adult = adult;
            this.children = children;
            this.infant = infant;
            this.username = username;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMonthlyTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMonthlyTicketResponse", Namespace="http://tempuri.org/", Order=0)]
        public VDMMutiline.APIExport.MonthSearch.GetMonthlyTicketResponseBody Body;
        
        public GetMonthlyTicketResponse() {
        }
        
        public GetMonthlyTicketResponse(VDMMutiline.APIExport.MonthSearch.GetMonthlyTicketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMonthlyTicketResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VDMMutiline.APIExport.MonthSearch.FlightFareInfo[] GetMonthlyTicketResult;
        
        public GetMonthlyTicketResponseBody() {
        }
        
        public GetMonthlyTicketResponseBody(VDMMutiline.APIExport.MonthSearch.FlightFareInfo[] GetMonthlyTicketResult) {
            this.GetMonthlyTicketResult = GetMonthlyTicketResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFlightFareInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFlightFareInfo", Namespace="http://tempuri.org/", Order=0)]
        public VDMMutiline.APIExport.MonthSearch.GetFlightFareInfoRequestBody Body;
        
        public GetFlightFareInfoRequest() {
        }
        
        public GetFlightFareInfoRequest(VDMMutiline.APIExport.MonthSearch.GetFlightFareInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFlightFareInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime datetime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string destinationAirportCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string departureAirportCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pass;
        
        public GetFlightFareInfoRequestBody() {
        }
        
        public GetFlightFareInfoRequestBody(System.DateTime datetime, string destinationAirportCode, string departureAirportCode, string username, string pass) {
            this.datetime = datetime;
            this.destinationAirportCode = destinationAirportCode;
            this.departureAirportCode = departureAirportCode;
            this.username = username;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFlightFareInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFlightFareInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public VDMMutiline.APIExport.MonthSearch.GetFlightFareInfoResponseBody Body;
        
        public GetFlightFareInfoResponse() {
        }
        
        public GetFlightFareInfoResponse(VDMMutiline.APIExport.MonthSearch.GetFlightFareInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFlightFareInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VDMMutiline.APIExport.MonthSearch.FlightFareInfo GetFlightFareInfoResult;
        
        public GetFlightFareInfoResponseBody() {
        }
        
        public GetFlightFareInfoResponseBody(VDMMutiline.APIExport.MonthSearch.FlightFareInfo GetFlightFareInfoResult) {
            this.GetFlightFareInfoResult = GetFlightFareInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetlisthancheRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Getlisthanche", Namespace="http://tempuri.org/", Order=0)]
        public VDMMutiline.APIExport.MonthSearch.GetlisthancheRequestBody Body;
        
        public GetlisthancheRequest() {
        }
        
        public GetlisthancheRequest(VDMMutiline.APIExport.MonthSearch.GetlisthancheRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetlisthancheRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hang;
        
        public GetlisthancheRequestBody() {
        }
        
        public GetlisthancheRequestBody(string hang) {
            this.hang = hang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetlisthancheResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetlisthancheResponse", Namespace="http://tempuri.org/", Order=0)]
        public VDMMutiline.APIExport.MonthSearch.GetlisthancheResponseBody Body;
        
        public GetlisthancheResponse() {
        }
        
        public GetlisthancheResponse(VDMMutiline.APIExport.MonthSearch.GetlisthancheResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetlisthancheResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VDMMutiline.APIExport.MonthSearch.HanchesohieuInfo[] GetlisthancheResult;
        
        public GetlisthancheResponseBody() {
        }
        
        public GetlisthancheResponseBody(VDMMutiline.APIExport.MonthSearch.HanchesohieuInfo[] GetlisthancheResult) {
            this.GetlisthancheResult = GetlisthancheResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetlisthancheAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetlisthancheAll", Namespace="http://tempuri.org/", Order=0)]
        public VDMMutiline.APIExport.MonthSearch.GetlisthancheAllRequestBody Body;
        
        public GetlisthancheAllRequest() {
        }
        
        public GetlisthancheAllRequest(VDMMutiline.APIExport.MonthSearch.GetlisthancheAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetlisthancheAllRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hang;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string hanve;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sohieu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string startpoint;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string endpoint;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double price;
        
        public GetlisthancheAllRequestBody() {
        }
        
        public GetlisthancheAllRequestBody(string hang, string hanve, string sohieu, string startpoint, string endpoint, double price) {
            this.hang = hang;
            this.hanve = hanve;
            this.sohieu = sohieu;
            this.startpoint = startpoint;
            this.endpoint = endpoint;
            this.price = price;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetlisthancheAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetlisthancheAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public VDMMutiline.APIExport.MonthSearch.GetlisthancheAllResponseBody Body;
        
        public GetlisthancheAllResponse() {
        }
        
        public GetlisthancheAllResponse(VDMMutiline.APIExport.MonthSearch.GetlisthancheAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetlisthancheAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VDMMutiline.APIExport.MonthSearch.HanchesohieuInfo[] GetlisthancheAllResult;
        
        public GetlisthancheAllResponseBody() {
        }
        
        public GetlisthancheAllResponseBody(VDMMutiline.APIExport.MonthSearch.HanchesohieuInfo[] GetlisthancheAllResult) {
            this.GetlisthancheAllResult = GetlisthancheAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetlistCauHinhTaiKhoanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetlistCauHinhTaiKhoan", Namespace="http://tempuri.org/", Order=0)]
        public VDMMutiline.APIExport.MonthSearch.GetlistCauHinhTaiKhoanRequestBody Body;
        
        public GetlistCauHinhTaiKhoanRequest() {
        }
        
        public GetlistCauHinhTaiKhoanRequest(VDMMutiline.APIExport.MonthSearch.GetlistCauHinhTaiKhoanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetlistCauHinhTaiKhoanRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hang;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string StartPoind;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EndPoind;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pass;
        
        public GetlistCauHinhTaiKhoanRequestBody() {
        }
        
        public GetlistCauHinhTaiKhoanRequestBody(string hang, string StartPoind, string EndPoind, string username, string pass) {
            this.hang = hang;
            this.StartPoind = StartPoind;
            this.EndPoind = EndPoind;
            this.username = username;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetlistCauHinhTaiKhoanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetlistCauHinhTaiKhoanResponse", Namespace="http://tempuri.org/", Order=0)]
        public VDMMutiline.APIExport.MonthSearch.GetlistCauHinhTaiKhoanResponseBody Body;
        
        public GetlistCauHinhTaiKhoanResponse() {
        }
        
        public GetlistCauHinhTaiKhoanResponse(VDMMutiline.APIExport.MonthSearch.GetlistCauHinhTaiKhoanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetlistCauHinhTaiKhoanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VDMMutiline.APIExport.MonthSearch.CauhinhtaikhoanInfo GetlistCauHinhTaiKhoanResult;
        
        public GetlistCauHinhTaiKhoanResponseBody() {
        }
        
        public GetlistCauHinhTaiKhoanResponseBody(VDMMutiline.APIExport.MonthSearch.CauhinhtaikhoanInfo GetlistCauHinhTaiKhoanResult) {
            this.GetlistCauHinhTaiKhoanResult = GetlistCauHinhTaiKhoanResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MonthSearchSoapChannel : VDMMutiline.APIExport.MonthSearch.MonthSearchSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonthSearchSoapClient : System.ServiceModel.ClientBase<VDMMutiline.APIExport.MonthSearch.MonthSearchSoap>, VDMMutiline.APIExport.MonthSearch.MonthSearchSoap {
        
        public MonthSearchSoapClient() {
        }
        
        public MonthSearchSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonthSearchSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonthSearchSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonthSearchSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VDMMutiline.APIExport.MonthSearch.GetMonthlyTicketResponse VDMMutiline.APIExport.MonthSearch.MonthSearchSoap.GetMonthlyTicket(VDMMutiline.APIExport.MonthSearch.GetMonthlyTicketRequest request) {
            return base.Channel.GetMonthlyTicket(request);
        }
        
        public VDMMutiline.APIExport.MonthSearch.FlightFareInfo[] GetMonthlyTicket(int mountvalue, int year, string destinationAirportCode, string departureAirportCode, int adult, int children, int infant, string username, string pass) {
            VDMMutiline.APIExport.MonthSearch.GetMonthlyTicketRequest inValue = new VDMMutiline.APIExport.MonthSearch.GetMonthlyTicketRequest();
            inValue.Body = new VDMMutiline.APIExport.MonthSearch.GetMonthlyTicketRequestBody();
            inValue.Body.mountvalue = mountvalue;
            inValue.Body.year = year;
            inValue.Body.destinationAirportCode = destinationAirportCode;
            inValue.Body.departureAirportCode = departureAirportCode;
            inValue.Body.adult = adult;
            inValue.Body.children = children;
            inValue.Body.infant = infant;
            inValue.Body.username = username;
            inValue.Body.pass = pass;
            VDMMutiline.APIExport.MonthSearch.GetMonthlyTicketResponse retVal = ((VDMMutiline.APIExport.MonthSearch.MonthSearchSoap)(this)).GetMonthlyTicket(inValue);
            return retVal.Body.GetMonthlyTicketResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VDMMutiline.APIExport.MonthSearch.GetMonthlyTicketResponse> VDMMutiline.APIExport.MonthSearch.MonthSearchSoap.GetMonthlyTicketAsync(VDMMutiline.APIExport.MonthSearch.GetMonthlyTicketRequest request) {
            return base.Channel.GetMonthlyTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<VDMMutiline.APIExport.MonthSearch.GetMonthlyTicketResponse> GetMonthlyTicketAsync(int mountvalue, int year, string destinationAirportCode, string departureAirportCode, int adult, int children, int infant, string username, string pass) {
            VDMMutiline.APIExport.MonthSearch.GetMonthlyTicketRequest inValue = new VDMMutiline.APIExport.MonthSearch.GetMonthlyTicketRequest();
            inValue.Body = new VDMMutiline.APIExport.MonthSearch.GetMonthlyTicketRequestBody();
            inValue.Body.mountvalue = mountvalue;
            inValue.Body.year = year;
            inValue.Body.destinationAirportCode = destinationAirportCode;
            inValue.Body.departureAirportCode = departureAirportCode;
            inValue.Body.adult = adult;
            inValue.Body.children = children;
            inValue.Body.infant = infant;
            inValue.Body.username = username;
            inValue.Body.pass = pass;
            return ((VDMMutiline.APIExport.MonthSearch.MonthSearchSoap)(this)).GetMonthlyTicketAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VDMMutiline.APIExport.MonthSearch.GetFlightFareInfoResponse VDMMutiline.APIExport.MonthSearch.MonthSearchSoap.GetFlightFareInfo(VDMMutiline.APIExport.MonthSearch.GetFlightFareInfoRequest request) {
            return base.Channel.GetFlightFareInfo(request);
        }
        
        public VDMMutiline.APIExport.MonthSearch.FlightFareInfo GetFlightFareInfo(System.DateTime datetime, string destinationAirportCode, string departureAirportCode, string username, string pass) {
            VDMMutiline.APIExport.MonthSearch.GetFlightFareInfoRequest inValue = new VDMMutiline.APIExport.MonthSearch.GetFlightFareInfoRequest();
            inValue.Body = new VDMMutiline.APIExport.MonthSearch.GetFlightFareInfoRequestBody();
            inValue.Body.datetime = datetime;
            inValue.Body.destinationAirportCode = destinationAirportCode;
            inValue.Body.departureAirportCode = departureAirportCode;
            inValue.Body.username = username;
            inValue.Body.pass = pass;
            VDMMutiline.APIExport.MonthSearch.GetFlightFareInfoResponse retVal = ((VDMMutiline.APIExport.MonthSearch.MonthSearchSoap)(this)).GetFlightFareInfo(inValue);
            return retVal.Body.GetFlightFareInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VDMMutiline.APIExport.MonthSearch.GetFlightFareInfoResponse> VDMMutiline.APIExport.MonthSearch.MonthSearchSoap.GetFlightFareInfoAsync(VDMMutiline.APIExport.MonthSearch.GetFlightFareInfoRequest request) {
            return base.Channel.GetFlightFareInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<VDMMutiline.APIExport.MonthSearch.GetFlightFareInfoResponse> GetFlightFareInfoAsync(System.DateTime datetime, string destinationAirportCode, string departureAirportCode, string username, string pass) {
            VDMMutiline.APIExport.MonthSearch.GetFlightFareInfoRequest inValue = new VDMMutiline.APIExport.MonthSearch.GetFlightFareInfoRequest();
            inValue.Body = new VDMMutiline.APIExport.MonthSearch.GetFlightFareInfoRequestBody();
            inValue.Body.datetime = datetime;
            inValue.Body.destinationAirportCode = destinationAirportCode;
            inValue.Body.departureAirportCode = departureAirportCode;
            inValue.Body.username = username;
            inValue.Body.pass = pass;
            return ((VDMMutiline.APIExport.MonthSearch.MonthSearchSoap)(this)).GetFlightFareInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VDMMutiline.APIExport.MonthSearch.GetlisthancheResponse VDMMutiline.APIExport.MonthSearch.MonthSearchSoap.Getlisthanche(VDMMutiline.APIExport.MonthSearch.GetlisthancheRequest request) {
            return base.Channel.Getlisthanche(request);
        }
        
        public VDMMutiline.APIExport.MonthSearch.HanchesohieuInfo[] Getlisthanche(string hang) {
            VDMMutiline.APIExport.MonthSearch.GetlisthancheRequest inValue = new VDMMutiline.APIExport.MonthSearch.GetlisthancheRequest();
            inValue.Body = new VDMMutiline.APIExport.MonthSearch.GetlisthancheRequestBody();
            inValue.Body.hang = hang;
            VDMMutiline.APIExport.MonthSearch.GetlisthancheResponse retVal = ((VDMMutiline.APIExport.MonthSearch.MonthSearchSoap)(this)).Getlisthanche(inValue);
            return retVal.Body.GetlisthancheResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VDMMutiline.APIExport.MonthSearch.GetlisthancheResponse> VDMMutiline.APIExport.MonthSearch.MonthSearchSoap.GetlisthancheAsync(VDMMutiline.APIExport.MonthSearch.GetlisthancheRequest request) {
            return base.Channel.GetlisthancheAsync(request);
        }
        
        public System.Threading.Tasks.Task<VDMMutiline.APIExport.MonthSearch.GetlisthancheResponse> GetlisthancheAsync(string hang) {
            VDMMutiline.APIExport.MonthSearch.GetlisthancheRequest inValue = new VDMMutiline.APIExport.MonthSearch.GetlisthancheRequest();
            inValue.Body = new VDMMutiline.APIExport.MonthSearch.GetlisthancheRequestBody();
            inValue.Body.hang = hang;
            return ((VDMMutiline.APIExport.MonthSearch.MonthSearchSoap)(this)).GetlisthancheAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VDMMutiline.APIExport.MonthSearch.GetlisthancheAllResponse VDMMutiline.APIExport.MonthSearch.MonthSearchSoap.GetlisthancheAll(VDMMutiline.APIExport.MonthSearch.GetlisthancheAllRequest request) {
            return base.Channel.GetlisthancheAll(request);
        }
        
        public VDMMutiline.APIExport.MonthSearch.HanchesohieuInfo[] GetlisthancheAll(string hang, string hanve, string sohieu, string startpoint, string endpoint, double price) {
            VDMMutiline.APIExport.MonthSearch.GetlisthancheAllRequest inValue = new VDMMutiline.APIExport.MonthSearch.GetlisthancheAllRequest();
            inValue.Body = new VDMMutiline.APIExport.MonthSearch.GetlisthancheAllRequestBody();
            inValue.Body.hang = hang;
            inValue.Body.hanve = hanve;
            inValue.Body.sohieu = sohieu;
            inValue.Body.startpoint = startpoint;
            inValue.Body.endpoint = endpoint;
            inValue.Body.price = price;
            VDMMutiline.APIExport.MonthSearch.GetlisthancheAllResponse retVal = ((VDMMutiline.APIExport.MonthSearch.MonthSearchSoap)(this)).GetlisthancheAll(inValue);
            return retVal.Body.GetlisthancheAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VDMMutiline.APIExport.MonthSearch.GetlisthancheAllResponse> VDMMutiline.APIExport.MonthSearch.MonthSearchSoap.GetlisthancheAllAsync(VDMMutiline.APIExport.MonthSearch.GetlisthancheAllRequest request) {
            return base.Channel.GetlisthancheAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<VDMMutiline.APIExport.MonthSearch.GetlisthancheAllResponse> GetlisthancheAllAsync(string hang, string hanve, string sohieu, string startpoint, string endpoint, double price) {
            VDMMutiline.APIExport.MonthSearch.GetlisthancheAllRequest inValue = new VDMMutiline.APIExport.MonthSearch.GetlisthancheAllRequest();
            inValue.Body = new VDMMutiline.APIExport.MonthSearch.GetlisthancheAllRequestBody();
            inValue.Body.hang = hang;
            inValue.Body.hanve = hanve;
            inValue.Body.sohieu = sohieu;
            inValue.Body.startpoint = startpoint;
            inValue.Body.endpoint = endpoint;
            inValue.Body.price = price;
            return ((VDMMutiline.APIExport.MonthSearch.MonthSearchSoap)(this)).GetlisthancheAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VDMMutiline.APIExport.MonthSearch.GetlistCauHinhTaiKhoanResponse VDMMutiline.APIExport.MonthSearch.MonthSearchSoap.GetlistCauHinhTaiKhoan(VDMMutiline.APIExport.MonthSearch.GetlistCauHinhTaiKhoanRequest request) {
            return base.Channel.GetlistCauHinhTaiKhoan(request);
        }
        
        public VDMMutiline.APIExport.MonthSearch.CauhinhtaikhoanInfo GetlistCauHinhTaiKhoan(string hang, string StartPoind, string EndPoind, string username, string pass) {
            VDMMutiline.APIExport.MonthSearch.GetlistCauHinhTaiKhoanRequest inValue = new VDMMutiline.APIExport.MonthSearch.GetlistCauHinhTaiKhoanRequest();
            inValue.Body = new VDMMutiline.APIExport.MonthSearch.GetlistCauHinhTaiKhoanRequestBody();
            inValue.Body.hang = hang;
            inValue.Body.StartPoind = StartPoind;
            inValue.Body.EndPoind = EndPoind;
            inValue.Body.username = username;
            inValue.Body.pass = pass;
            VDMMutiline.APIExport.MonthSearch.GetlistCauHinhTaiKhoanResponse retVal = ((VDMMutiline.APIExport.MonthSearch.MonthSearchSoap)(this)).GetlistCauHinhTaiKhoan(inValue);
            return retVal.Body.GetlistCauHinhTaiKhoanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VDMMutiline.APIExport.MonthSearch.GetlistCauHinhTaiKhoanResponse> VDMMutiline.APIExport.MonthSearch.MonthSearchSoap.GetlistCauHinhTaiKhoanAsync(VDMMutiline.APIExport.MonthSearch.GetlistCauHinhTaiKhoanRequest request) {
            return base.Channel.GetlistCauHinhTaiKhoanAsync(request);
        }
        
        public System.Threading.Tasks.Task<VDMMutiline.APIExport.MonthSearch.GetlistCauHinhTaiKhoanResponse> GetlistCauHinhTaiKhoanAsync(string hang, string StartPoind, string EndPoind, string username, string pass) {
            VDMMutiline.APIExport.MonthSearch.GetlistCauHinhTaiKhoanRequest inValue = new VDMMutiline.APIExport.MonthSearch.GetlistCauHinhTaiKhoanRequest();
            inValue.Body = new VDMMutiline.APIExport.MonthSearch.GetlistCauHinhTaiKhoanRequestBody();
            inValue.Body.hang = hang;
            inValue.Body.StartPoind = StartPoind;
            inValue.Body.EndPoind = EndPoind;
            inValue.Body.username = username;
            inValue.Body.pass = pass;
            return ((VDMMutiline.APIExport.MonthSearch.MonthSearchSoap)(this)).GetlistCauHinhTaiKhoanAsync(inValue);
        }
    }
}
