#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingResponse.Database.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Vdm_Mutiline_TGVR")]
	public partial class BookingDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblBookResponseFareData(tblBookResponseFareData instance);
    partial void UpdatetblBookResponseFareData(tblBookResponseFareData instance);
    partial void DeletetblBookResponseFareData(tblBookResponseFareData instance);
    partial void InserttblBookResponseBooking(tblBookResponseBooking instance);
    partial void UpdatetblBookResponseBooking(tblBookResponseBooking instance);
    partial void DeletetblBookResponseBooking(tblBookResponseBooking instance);
    partial void InserttblBookResponseTicket(tblBookResponseTicket instance);
    partial void UpdatetblBookResponseTicket(tblBookResponseTicket instance);
    partial void DeletetblBookResponseTicket(tblBookResponseTicket instance);
    partial void InserttblBookResponseFlight(tblBookResponseFlight instance);
    partial void UpdatetblBookResponseFlight(tblBookResponseFlight instance);
    partial void DeletetblBookResponseFlight(tblBookResponseFlight instance);
    partial void InserttblBookResponseSegment(tblBookResponseSegment instance);
    partial void UpdatetblBookResponseSegment(tblBookResponseSegment instance);
    partial void DeletetblBookResponseSegment(tblBookResponseSegment instance);
    partial void InserttblBookResponse(tblBookResponse instance);
    partial void UpdatetblBookResponse(tblBookResponse instance);
    partial void DeletetblBookResponse(tblBookResponse instance);
    #endregion
		
		public BookingDataDataContext() : 
				base(global::BookingResponse.Database.Properties.Settings.Default.Vdm_Mutiline_TGVRConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public BookingDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BookingDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BookingDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BookingDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblBookResponseFareData> tblBookResponseFareDatas
		{
			get
			{
				return this.GetTable<tblBookResponseFareData>();
			}
		}
		
		public System.Data.Linq.Table<tblBookResponseBooking> tblBookResponseBookings
		{
			get
			{
				return this.GetTable<tblBookResponseBooking>();
			}
		}
		
		public System.Data.Linq.Table<tblBookResponseTicket> tblBookResponseTickets
		{
			get
			{
				return this.GetTable<tblBookResponseTicket>();
			}
		}
		
		public System.Data.Linq.Table<tblBookResponseFlight> tblBookResponseFlights
		{
			get
			{
				return this.GetTable<tblBookResponseFlight>();
			}
		}
		
		public System.Data.Linq.Table<tblBookResponseSegment> tblBookResponseSegments
		{
			get
			{
				return this.GetTable<tblBookResponseSegment>();
			}
		}
		
		public System.Data.Linq.Table<tblBookResponse> tblBookResponses
		{
			get
			{
				return this.GetTable<tblBookResponse>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblBookResponseFareData")]
	public partial class tblBookResponseFareData : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _FareDataId;
		
		private System.Nullable<int> _BookingId;
		
		private string _Airline;
		
		private System.Nullable<int> _Itinerary;
		
		private System.Nullable<int> _Leg;
		
		private System.Nullable<bool> _Promo;
		
		private string _Currency;
		
		private string _System;
		
		private string _FareType;
		
		private System.Nullable<decimal> _CacheAge;
		
		private System.Nullable<int> _Adt;
		
		private System.Nullable<int> _Chd;
		
		private System.Nullable<int> _Inf;
		
		private System.Nullable<decimal> _FareAdt;
		
		private System.Nullable<decimal> _FareChd;
		
		private System.Nullable<decimal> _FareInf;
		
		private System.Nullable<decimal> _TaxAdt;
		
		private System.Nullable<decimal> _TaxChd;
		
		private System.Nullable<decimal> _TaxInf;
		
		private System.Nullable<decimal> _FeeAdt;
		
		private System.Nullable<decimal> _FeeChd;
		
		private System.Nullable<decimal> _FeeInf;
		
		private System.Nullable<decimal> _ServiceFeeAdt;
		
		private System.Nullable<decimal> _ServiceFeeChd;
		
		private System.Nullable<decimal> _ServiceFeeInf;
		
		private System.Nullable<decimal> _TotalNetPrice;
		
		private System.Nullable<decimal> _TotalServiceFee;
		
		private System.Nullable<decimal> _TotalDiscount;
		
		private System.Nullable<decimal> _TotalCommission;
		
		private System.Nullable<decimal> _TotalPrice;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFareDataIdChanging(System.Nullable<int> value);
    partial void OnFareDataIdChanged();
    partial void OnBookingIdChanging(System.Nullable<int> value);
    partial void OnBookingIdChanged();
    partial void OnAirlineChanging(string value);
    partial void OnAirlineChanged();
    partial void OnItineraryChanging(System.Nullable<int> value);
    partial void OnItineraryChanged();
    partial void OnLegChanging(System.Nullable<int> value);
    partial void OnLegChanged();
    partial void OnPromoChanging(System.Nullable<bool> value);
    partial void OnPromoChanged();
    partial void OnCurrencyChanging(string value);
    partial void OnCurrencyChanged();
    partial void OnSystemChanging(string value);
    partial void OnSystemChanged();
    partial void OnFareTypeChanging(string value);
    partial void OnFareTypeChanged();
    partial void OnCacheAgeChanging(System.Nullable<decimal> value);
    partial void OnCacheAgeChanged();
    partial void OnAdtChanging(System.Nullable<int> value);
    partial void OnAdtChanged();
    partial void OnChdChanging(System.Nullable<int> value);
    partial void OnChdChanged();
    partial void OnInfChanging(System.Nullable<int> value);
    partial void OnInfChanged();
    partial void OnFareAdtChanging(System.Nullable<decimal> value);
    partial void OnFareAdtChanged();
    partial void OnFareChdChanging(System.Nullable<decimal> value);
    partial void OnFareChdChanged();
    partial void OnFareInfChanging(System.Nullable<decimal> value);
    partial void OnFareInfChanged();
    partial void OnTaxAdtChanging(System.Nullable<decimal> value);
    partial void OnTaxAdtChanged();
    partial void OnTaxChdChanging(System.Nullable<decimal> value);
    partial void OnTaxChdChanged();
    partial void OnTaxInfChanging(System.Nullable<decimal> value);
    partial void OnTaxInfChanged();
    partial void OnFeeAdtChanging(System.Nullable<decimal> value);
    partial void OnFeeAdtChanged();
    partial void OnFeeChdChanging(System.Nullable<decimal> value);
    partial void OnFeeChdChanged();
    partial void OnFeeInfChanging(System.Nullable<decimal> value);
    partial void OnFeeInfChanged();
    partial void OnServiceFeeAdtChanging(System.Nullable<decimal> value);
    partial void OnServiceFeeAdtChanged();
    partial void OnServiceFeeChdChanging(System.Nullable<decimal> value);
    partial void OnServiceFeeChdChanged();
    partial void OnServiceFeeInfChanging(System.Nullable<decimal> value);
    partial void OnServiceFeeInfChanged();
    partial void OnTotalNetPriceChanging(System.Nullable<decimal> value);
    partial void OnTotalNetPriceChanged();
    partial void OnTotalServiceFeeChanging(System.Nullable<decimal> value);
    partial void OnTotalServiceFeeChanged();
    partial void OnTotalDiscountChanging(System.Nullable<decimal> value);
    partial void OnTotalDiscountChanged();
    partial void OnTotalCommissionChanging(System.Nullable<decimal> value);
    partial void OnTotalCommissionChanged();
    partial void OnTotalPriceChanging(System.Nullable<decimal> value);
    partial void OnTotalPriceChanged();
    #endregion
		
		public tblBookResponseFareData()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FareDataId", DbType="Int")]
		public System.Nullable<int> FareDataId
		{
			get
			{
				return this._FareDataId;
			}
			set
			{
				if ((this._FareDataId != value))
				{
					this.OnFareDataIdChanging(value);
					this.SendPropertyChanging();
					this._FareDataId = value;
					this.SendPropertyChanged("FareDataId");
					this.OnFareDataIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookingId", DbType="Int")]
		public System.Nullable<int> BookingId
		{
			get
			{
				return this._BookingId;
			}
			set
			{
				if ((this._BookingId != value))
				{
					this.OnBookingIdChanging(value);
					this.SendPropertyChanging();
					this._BookingId = value;
					this.SendPropertyChanged("BookingId");
					this.OnBookingIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Airline", DbType="NVarChar(50)")]
		public string Airline
		{
			get
			{
				return this._Airline;
			}
			set
			{
				if ((this._Airline != value))
				{
					this.OnAirlineChanging(value);
					this.SendPropertyChanging();
					this._Airline = value;
					this.SendPropertyChanged("Airline");
					this.OnAirlineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Itinerary", DbType="Int")]
		public System.Nullable<int> Itinerary
		{
			get
			{
				return this._Itinerary;
			}
			set
			{
				if ((this._Itinerary != value))
				{
					this.OnItineraryChanging(value);
					this.SendPropertyChanging();
					this._Itinerary = value;
					this.SendPropertyChanged("Itinerary");
					this.OnItineraryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Leg", DbType="Int")]
		public System.Nullable<int> Leg
		{
			get
			{
				return this._Leg;
			}
			set
			{
				if ((this._Leg != value))
				{
					this.OnLegChanging(value);
					this.SendPropertyChanging();
					this._Leg = value;
					this.SendPropertyChanged("Leg");
					this.OnLegChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Promo", DbType="Bit")]
		public System.Nullable<bool> Promo
		{
			get
			{
				return this._Promo;
			}
			set
			{
				if ((this._Promo != value))
				{
					this.OnPromoChanging(value);
					this.SendPropertyChanging();
					this._Promo = value;
					this.SendPropertyChanged("Promo");
					this.OnPromoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Currency", DbType="NVarChar(50)")]
		public string Currency
		{
			get
			{
				return this._Currency;
			}
			set
			{
				if ((this._Currency != value))
				{
					this.OnCurrencyChanging(value);
					this.SendPropertyChanging();
					this._Currency = value;
					this.SendPropertyChanged("Currency");
					this.OnCurrencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_System", DbType="NVarChar(500)")]
		public string System
		{
			get
			{
				return this._System;
			}
			set
			{
				if ((this._System != value))
				{
					this.OnSystemChanging(value);
					this.SendPropertyChanging();
					this._System = value;
					this.SendPropertyChanged("System");
					this.OnSystemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FareType", DbType="NVarChar(500)")]
		public string FareType
		{
			get
			{
				return this._FareType;
			}
			set
			{
				if ((this._FareType != value))
				{
					this.OnFareTypeChanging(value);
					this.SendPropertyChanging();
					this._FareType = value;
					this.SendPropertyChanged("FareType");
					this.OnFareTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CacheAge", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CacheAge
		{
			get
			{
				return this._CacheAge;
			}
			set
			{
				if ((this._CacheAge != value))
				{
					this.OnCacheAgeChanging(value);
					this.SendPropertyChanging();
					this._CacheAge = value;
					this.SendPropertyChanged("CacheAge");
					this.OnCacheAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adt", DbType="Int")]
		public System.Nullable<int> Adt
		{
			get
			{
				return this._Adt;
			}
			set
			{
				if ((this._Adt != value))
				{
					this.OnAdtChanging(value);
					this.SendPropertyChanging();
					this._Adt = value;
					this.SendPropertyChanged("Adt");
					this.OnAdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chd", DbType="Int")]
		public System.Nullable<int> Chd
		{
			get
			{
				return this._Chd;
			}
			set
			{
				if ((this._Chd != value))
				{
					this.OnChdChanging(value);
					this.SendPropertyChanging();
					this._Chd = value;
					this.SendPropertyChanged("Chd");
					this.OnChdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inf", DbType="Int")]
		public System.Nullable<int> Inf
		{
			get
			{
				return this._Inf;
			}
			set
			{
				if ((this._Inf != value))
				{
					this.OnInfChanging(value);
					this.SendPropertyChanging();
					this._Inf = value;
					this.SendPropertyChanged("Inf");
					this.OnInfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FareAdt", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> FareAdt
		{
			get
			{
				return this._FareAdt;
			}
			set
			{
				if ((this._FareAdt != value))
				{
					this.OnFareAdtChanging(value);
					this.SendPropertyChanging();
					this._FareAdt = value;
					this.SendPropertyChanged("FareAdt");
					this.OnFareAdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FareChd", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> FareChd
		{
			get
			{
				return this._FareChd;
			}
			set
			{
				if ((this._FareChd != value))
				{
					this.OnFareChdChanging(value);
					this.SendPropertyChanging();
					this._FareChd = value;
					this.SendPropertyChanged("FareChd");
					this.OnFareChdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FareInf", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> FareInf
		{
			get
			{
				return this._FareInf;
			}
			set
			{
				if ((this._FareInf != value))
				{
					this.OnFareInfChanging(value);
					this.SendPropertyChanging();
					this._FareInf = value;
					this.SendPropertyChanged("FareInf");
					this.OnFareInfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxAdt", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TaxAdt
		{
			get
			{
				return this._TaxAdt;
			}
			set
			{
				if ((this._TaxAdt != value))
				{
					this.OnTaxAdtChanging(value);
					this.SendPropertyChanging();
					this._TaxAdt = value;
					this.SendPropertyChanged("TaxAdt");
					this.OnTaxAdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxChd", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TaxChd
		{
			get
			{
				return this._TaxChd;
			}
			set
			{
				if ((this._TaxChd != value))
				{
					this.OnTaxChdChanging(value);
					this.SendPropertyChanging();
					this._TaxChd = value;
					this.SendPropertyChanged("TaxChd");
					this.OnTaxChdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxInf", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TaxInf
		{
			get
			{
				return this._TaxInf;
			}
			set
			{
				if ((this._TaxInf != value))
				{
					this.OnTaxInfChanging(value);
					this.SendPropertyChanging();
					this._TaxInf = value;
					this.SendPropertyChanged("TaxInf");
					this.OnTaxInfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeeAdt", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> FeeAdt
		{
			get
			{
				return this._FeeAdt;
			}
			set
			{
				if ((this._FeeAdt != value))
				{
					this.OnFeeAdtChanging(value);
					this.SendPropertyChanging();
					this._FeeAdt = value;
					this.SendPropertyChanged("FeeAdt");
					this.OnFeeAdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeeChd", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> FeeChd
		{
			get
			{
				return this._FeeChd;
			}
			set
			{
				if ((this._FeeChd != value))
				{
					this.OnFeeChdChanging(value);
					this.SendPropertyChanging();
					this._FeeChd = value;
					this.SendPropertyChanged("FeeChd");
					this.OnFeeChdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeeInf", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> FeeInf
		{
			get
			{
				return this._FeeInf;
			}
			set
			{
				if ((this._FeeInf != value))
				{
					this.OnFeeInfChanging(value);
					this.SendPropertyChanging();
					this._FeeInf = value;
					this.SendPropertyChanged("FeeInf");
					this.OnFeeInfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceFeeAdt", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ServiceFeeAdt
		{
			get
			{
				return this._ServiceFeeAdt;
			}
			set
			{
				if ((this._ServiceFeeAdt != value))
				{
					this.OnServiceFeeAdtChanging(value);
					this.SendPropertyChanging();
					this._ServiceFeeAdt = value;
					this.SendPropertyChanged("ServiceFeeAdt");
					this.OnServiceFeeAdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceFeeChd", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ServiceFeeChd
		{
			get
			{
				return this._ServiceFeeChd;
			}
			set
			{
				if ((this._ServiceFeeChd != value))
				{
					this.OnServiceFeeChdChanging(value);
					this.SendPropertyChanging();
					this._ServiceFeeChd = value;
					this.SendPropertyChanged("ServiceFeeChd");
					this.OnServiceFeeChdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceFeeInf", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ServiceFeeInf
		{
			get
			{
				return this._ServiceFeeInf;
			}
			set
			{
				if ((this._ServiceFeeInf != value))
				{
					this.OnServiceFeeInfChanging(value);
					this.SendPropertyChanging();
					this._ServiceFeeInf = value;
					this.SendPropertyChanged("ServiceFeeInf");
					this.OnServiceFeeInfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalNetPrice", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TotalNetPrice
		{
			get
			{
				return this._TotalNetPrice;
			}
			set
			{
				if ((this._TotalNetPrice != value))
				{
					this.OnTotalNetPriceChanging(value);
					this.SendPropertyChanging();
					this._TotalNetPrice = value;
					this.SendPropertyChanged("TotalNetPrice");
					this.OnTotalNetPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalServiceFee", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TotalServiceFee
		{
			get
			{
				return this._TotalServiceFee;
			}
			set
			{
				if ((this._TotalServiceFee != value))
				{
					this.OnTotalServiceFeeChanging(value);
					this.SendPropertyChanging();
					this._TotalServiceFee = value;
					this.SendPropertyChanged("TotalServiceFee");
					this.OnTotalServiceFeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalDiscount", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TotalDiscount
		{
			get
			{
				return this._TotalDiscount;
			}
			set
			{
				if ((this._TotalDiscount != value))
				{
					this.OnTotalDiscountChanging(value);
					this.SendPropertyChanging();
					this._TotalDiscount = value;
					this.SendPropertyChanged("TotalDiscount");
					this.OnTotalDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalCommission", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TotalCommission
		{
			get
			{
				return this._TotalCommission;
			}
			set
			{
				if ((this._TotalCommission != value))
				{
					this.OnTotalCommissionChanging(value);
					this.SendPropertyChanging();
					this._TotalCommission = value;
					this.SendPropertyChanged("TotalCommission");
					this.OnTotalCommissionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalPrice", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TotalPrice
		{
			get
			{
				return this._TotalPrice;
			}
			set
			{
				if ((this._TotalPrice != value))
				{
					this.OnTotalPriceChanging(value);
					this.SendPropertyChanging();
					this._TotalPrice = value;
					this.SendPropertyChanged("TotalPrice");
					this.OnTotalPriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblBookResponseBooking")]
	public partial class tblBookResponseBooking : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _BookingId;
		
		private string _Status;
		
		private System.Nullable<bool> _AutoIssue;
		
		private string _Airline;
		
		private string _BookingCode;
		
		private string _GdsCode;
		
		private string _Flight;
		
		private string _Route;
		
		private string _ErrorCode;
		
		private string _ErrorMessage;
		
		private string _BookingImage;
		
		private System.Nullable<System.DateTime> _ExpiryDate;
		
		private string _ExpiryDt;
		
		private System.Nullable<int> _ExpiryTime;
		
		private System.Nullable<decimal> _ResponseTime;
		
		private string _System;
		
		private System.Nullable<decimal> _Price;
		
		private System.Nullable<decimal> _Difference;
		
		private string _Session;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBookingIdChanging(System.Nullable<int> value);
    partial void OnBookingIdChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnAutoIssueChanging(System.Nullable<bool> value);
    partial void OnAutoIssueChanged();
    partial void OnAirlineChanging(string value);
    partial void OnAirlineChanged();
    partial void OnBookingCodeChanging(string value);
    partial void OnBookingCodeChanged();
    partial void OnGdsCodeChanging(string value);
    partial void OnGdsCodeChanged();
    partial void OnFlightChanging(string value);
    partial void OnFlightChanged();
    partial void OnRouteChanging(string value);
    partial void OnRouteChanged();
    partial void OnErrorCodeChanging(string value);
    partial void OnErrorCodeChanged();
    partial void OnErrorMessageChanging(string value);
    partial void OnErrorMessageChanged();
    partial void OnBookingImageChanging(string value);
    partial void OnBookingImageChanged();
    partial void OnExpiryDateChanging(System.Nullable<System.DateTime> value);
    partial void OnExpiryDateChanged();
    partial void OnExpiryDtChanging(string value);
    partial void OnExpiryDtChanged();
    partial void OnExpiryTimeChanging(System.Nullable<int> value);
    partial void OnExpiryTimeChanged();
    partial void OnResponseTimeChanging(System.Nullable<decimal> value);
    partial void OnResponseTimeChanged();
    partial void OnSystemChanging(string value);
    partial void OnSystemChanged();
    partial void OnPriceChanging(System.Nullable<decimal> value);
    partial void OnPriceChanged();
    partial void OnDifferenceChanging(System.Nullable<decimal> value);
    partial void OnDifferenceChanged();
    partial void OnSessionChanging(string value);
    partial void OnSessionChanged();
    #endregion
		
		public tblBookResponseBooking()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookingId", DbType="Int")]
		public System.Nullable<int> BookingId
		{
			get
			{
				return this._BookingId;
			}
			set
			{
				if ((this._BookingId != value))
				{
					this.OnBookingIdChanging(value);
					this.SendPropertyChanging();
					this._BookingId = value;
					this.SendPropertyChanged("BookingId");
					this.OnBookingIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(MAX)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoIssue", DbType="Bit")]
		public System.Nullable<bool> AutoIssue
		{
			get
			{
				return this._AutoIssue;
			}
			set
			{
				if ((this._AutoIssue != value))
				{
					this.OnAutoIssueChanging(value);
					this.SendPropertyChanging();
					this._AutoIssue = value;
					this.SendPropertyChanged("AutoIssue");
					this.OnAutoIssueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Airline", DbType="NVarChar(50)")]
		public string Airline
		{
			get
			{
				return this._Airline;
			}
			set
			{
				if ((this._Airline != value))
				{
					this.OnAirlineChanging(value);
					this.SendPropertyChanging();
					this._Airline = value;
					this.SendPropertyChanged("Airline");
					this.OnAirlineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookingCode", DbType="NVarChar(50)")]
		public string BookingCode
		{
			get
			{
				return this._BookingCode;
			}
			set
			{
				if ((this._BookingCode != value))
				{
					this.OnBookingCodeChanging(value);
					this.SendPropertyChanging();
					this._BookingCode = value;
					this.SendPropertyChanged("BookingCode");
					this.OnBookingCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GdsCode", DbType="NVarChar(500)")]
		public string GdsCode
		{
			get
			{
				return this._GdsCode;
			}
			set
			{
				if ((this._GdsCode != value))
				{
					this.OnGdsCodeChanging(value);
					this.SendPropertyChanging();
					this._GdsCode = value;
					this.SendPropertyChanged("GdsCode");
					this.OnGdsCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flight", DbType="NVarChar(500)")]
		public string Flight
		{
			get
			{
				return this._Flight;
			}
			set
			{
				if ((this._Flight != value))
				{
					this.OnFlightChanging(value);
					this.SendPropertyChanging();
					this._Flight = value;
					this.SendPropertyChanged("Flight");
					this.OnFlightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Route", DbType="NVarChar(MAX)")]
		public string Route
		{
			get
			{
				return this._Route;
			}
			set
			{
				if ((this._Route != value))
				{
					this.OnRouteChanging(value);
					this.SendPropertyChanging();
					this._Route = value;
					this.SendPropertyChanged("Route");
					this.OnRouteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorCode", DbType="NVarChar(MAX)")]
		public string ErrorCode
		{
			get
			{
				return this._ErrorCode;
			}
			set
			{
				if ((this._ErrorCode != value))
				{
					this.OnErrorCodeChanging(value);
					this.SendPropertyChanging();
					this._ErrorCode = value;
					this.SendPropertyChanged("ErrorCode");
					this.OnErrorCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorMessage", DbType="NVarChar(MAX)")]
		public string ErrorMessage
		{
			get
			{
				return this._ErrorMessage;
			}
			set
			{
				if ((this._ErrorMessage != value))
				{
					this.OnErrorMessageChanging(value);
					this.SendPropertyChanging();
					this._ErrorMessage = value;
					this.SendPropertyChanged("ErrorMessage");
					this.OnErrorMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookingImage", DbType="NVarChar(MAX)")]
		public string BookingImage
		{
			get
			{
				return this._BookingImage;
			}
			set
			{
				if ((this._BookingImage != value))
				{
					this.OnBookingImageChanging(value);
					this.SendPropertyChanging();
					this._BookingImage = value;
					this.SendPropertyChanged("BookingImage");
					this.OnBookingImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiryDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpiryDate
		{
			get
			{
				return this._ExpiryDate;
			}
			set
			{
				if ((this._ExpiryDate != value))
				{
					this.OnExpiryDateChanging(value);
					this.SendPropertyChanging();
					this._ExpiryDate = value;
					this.SendPropertyChanged("ExpiryDate");
					this.OnExpiryDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiryDt", DbType="NVarChar(MAX)")]
		public string ExpiryDt
		{
			get
			{
				return this._ExpiryDt;
			}
			set
			{
				if ((this._ExpiryDt != value))
				{
					this.OnExpiryDtChanging(value);
					this.SendPropertyChanging();
					this._ExpiryDt = value;
					this.SendPropertyChanged("ExpiryDt");
					this.OnExpiryDtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiryTime", DbType="Int")]
		public System.Nullable<int> ExpiryTime
		{
			get
			{
				return this._ExpiryTime;
			}
			set
			{
				if ((this._ExpiryTime != value))
				{
					this.OnExpiryTimeChanging(value);
					this.SendPropertyChanging();
					this._ExpiryTime = value;
					this.SendPropertyChanged("ExpiryTime");
					this.OnExpiryTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResponseTime", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ResponseTime
		{
			get
			{
				return this._ResponseTime;
			}
			set
			{
				if ((this._ResponseTime != value))
				{
					this.OnResponseTimeChanging(value);
					this.SendPropertyChanging();
					this._ResponseTime = value;
					this.SendPropertyChanged("ResponseTime");
					this.OnResponseTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_System", DbType="NVarChar(50)")]
		public string System
		{
			get
			{
				return this._System;
			}
			set
			{
				if ((this._System != value))
				{
					this.OnSystemChanging(value);
					this.SendPropertyChanging();
					this._System = value;
					this.SendPropertyChanged("System");
					this.OnSystemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Difference", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Difference
		{
			get
			{
				return this._Difference;
			}
			set
			{
				if ((this._Difference != value))
				{
					this.OnDifferenceChanging(value);
					this.SendPropertyChanging();
					this._Difference = value;
					this.SendPropertyChanged("Difference");
					this.OnDifferenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Session", DbType="NVarChar(MAX)")]
		public string Session
		{
			get
			{
				return this._Session;
			}
			set
			{
				if ((this._Session != value))
				{
					this.OnSessionChanging(value);
					this.SendPropertyChanging();
					this._Session = value;
					this.SendPropertyChanged("Session");
					this.OnSessionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblBookResponseTicket")]
	public partial class tblBookResponseTicket : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _BookingId;
		
		private System.Nullable<int> _Index;
		
		private string _Airline;
		
		private string _TicketNumber;
		
		private System.Nullable<System.DateTime> _IssueDate;
		
		private string _BookingCode;
		
		private string _PassengerName;
		
		private string _BookingFile;
		
		private string _TicketImage;
		
		private System.Nullable<decimal> _TotalPrice;
		
		private string _Status;
		
		private string _ErrorMessage;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBookingIdChanging(System.Nullable<int> value);
    partial void OnBookingIdChanged();
    partial void OnIndexChanging(System.Nullable<int> value);
    partial void OnIndexChanged();
    partial void OnAirlineChanging(string value);
    partial void OnAirlineChanged();
    partial void OnTicketNumberChanging(string value);
    partial void OnTicketNumberChanged();
    partial void OnIssueDateChanging(System.Nullable<System.DateTime> value);
    partial void OnIssueDateChanged();
    partial void OnBookingCodeChanging(string value);
    partial void OnBookingCodeChanged();
    partial void OnPassengerNameChanging(string value);
    partial void OnPassengerNameChanged();
    partial void OnBookingFileChanging(string value);
    partial void OnBookingFileChanged();
    partial void OnTicketImageChanging(string value);
    partial void OnTicketImageChanged();
    partial void OnTotalPriceChanging(System.Nullable<decimal> value);
    partial void OnTotalPriceChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnErrorMessageChanging(string value);
    partial void OnErrorMessageChanged();
    #endregion
		
		public tblBookResponseTicket()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookingId", DbType="Int")]
		public System.Nullable<int> BookingId
		{
			get
			{
				return this._BookingId;
			}
			set
			{
				if ((this._BookingId != value))
				{
					this.OnBookingIdChanging(value);
					this.SendPropertyChanging();
					this._BookingId = value;
					this.SendPropertyChanged("BookingId");
					this.OnBookingIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Index]", Storage="_Index", DbType="Int")]
		public System.Nullable<int> Index
		{
			get
			{
				return this._Index;
			}
			set
			{
				if ((this._Index != value))
				{
					this.OnIndexChanging(value);
					this.SendPropertyChanging();
					this._Index = value;
					this.SendPropertyChanged("Index");
					this.OnIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Airline", DbType="NVarChar(500)")]
		public string Airline
		{
			get
			{
				return this._Airline;
			}
			set
			{
				if ((this._Airline != value))
				{
					this.OnAirlineChanging(value);
					this.SendPropertyChanging();
					this._Airline = value;
					this.SendPropertyChanged("Airline");
					this.OnAirlineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TicketNumber", DbType="NVarChar(500)")]
		public string TicketNumber
		{
			get
			{
				return this._TicketNumber;
			}
			set
			{
				if ((this._TicketNumber != value))
				{
					this.OnTicketNumberChanging(value);
					this.SendPropertyChanging();
					this._TicketNumber = value;
					this.SendPropertyChanged("TicketNumber");
					this.OnTicketNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IssueDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> IssueDate
		{
			get
			{
				return this._IssueDate;
			}
			set
			{
				if ((this._IssueDate != value))
				{
					this.OnIssueDateChanging(value);
					this.SendPropertyChanging();
					this._IssueDate = value;
					this.SendPropertyChanged("IssueDate");
					this.OnIssueDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookingCode", DbType="NVarChar(50)")]
		public string BookingCode
		{
			get
			{
				return this._BookingCode;
			}
			set
			{
				if ((this._BookingCode != value))
				{
					this.OnBookingCodeChanging(value);
					this.SendPropertyChanging();
					this._BookingCode = value;
					this.SendPropertyChanged("BookingCode");
					this.OnBookingCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassengerName", DbType="NVarChar(500)")]
		public string PassengerName
		{
			get
			{
				return this._PassengerName;
			}
			set
			{
				if ((this._PassengerName != value))
				{
					this.OnPassengerNameChanging(value);
					this.SendPropertyChanging();
					this._PassengerName = value;
					this.SendPropertyChanged("PassengerName");
					this.OnPassengerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookingFile", DbType="NVarChar(MAX)")]
		public string BookingFile
		{
			get
			{
				return this._BookingFile;
			}
			set
			{
				if ((this._BookingFile != value))
				{
					this.OnBookingFileChanging(value);
					this.SendPropertyChanging();
					this._BookingFile = value;
					this.SendPropertyChanged("BookingFile");
					this.OnBookingFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TicketImage", DbType="NVarChar(MAX)")]
		public string TicketImage
		{
			get
			{
				return this._TicketImage;
			}
			set
			{
				if ((this._TicketImage != value))
				{
					this.OnTicketImageChanging(value);
					this.SendPropertyChanging();
					this._TicketImage = value;
					this.SendPropertyChanged("TicketImage");
					this.OnTicketImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalPrice", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TotalPrice
		{
			get
			{
				return this._TotalPrice;
			}
			set
			{
				if ((this._TotalPrice != value))
				{
					this.OnTotalPriceChanging(value);
					this.SendPropertyChanging();
					this._TotalPrice = value;
					this.SendPropertyChanged("TotalPrice");
					this.OnTotalPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(MAX)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorMessage", DbType="NChar(10)")]
		public string ErrorMessage
		{
			get
			{
				return this._ErrorMessage;
			}
			set
			{
				if ((this._ErrorMessage != value))
				{
					this.OnErrorMessageChanging(value);
					this.SendPropertyChanging();
					this._ErrorMessage = value;
					this.SendPropertyChanged("ErrorMessage");
					this.OnErrorMessageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblBookResponseFlight")]
	public partial class tblBookResponseFlight : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _BookingId;
		
		private System.Nullable<int> _FareDataId;
		
		private System.Nullable<int> _FlightId;
		
		private System.Nullable<int> _Leg;
		
		private string _Airline;
		
		private string _Operating;
		
		private string _StartPoint;
		
		private string _EndPoint;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private string _StartDt;
		
		private string _EndDt;
		
		private string _FlightNumber;
		
		private System.Nullable<int> _StopNum;
		
		private System.Nullable<bool> _HasDownStop;
		
		private System.Nullable<int> _Duration;
		
		private System.Nullable<bool> _NoRefund;
		
		private string _GroupClass;
		
		private string _FareClass;
		
		private string _FareBasis;
		
		private System.Nullable<int> _SeatRemain;
		
		private System.Nullable<bool> _Promo;
		
		private string _FlightValue;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBookingIdChanging(System.Nullable<int> value);
    partial void OnBookingIdChanged();
    partial void OnFareDataIdChanging(System.Nullable<int> value);
    partial void OnFareDataIdChanged();
    partial void OnFlightIdChanging(System.Nullable<int> value);
    partial void OnFlightIdChanged();
    partial void OnLegChanging(System.Nullable<int> value);
    partial void OnLegChanged();
    partial void OnAirlineChanging(string value);
    partial void OnAirlineChanged();
    partial void OnOperatingChanging(string value);
    partial void OnOperatingChanged();
    partial void OnStartPointChanging(string value);
    partial void OnStartPointChanged();
    partial void OnEndPointChanging(string value);
    partial void OnEndPointChanged();
    partial void OnStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStartDateChanged();
    partial void OnEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEndDateChanged();
    partial void OnStartDtChanging(string value);
    partial void OnStartDtChanged();
    partial void OnEndDtChanging(string value);
    partial void OnEndDtChanged();
    partial void OnFlightNumberChanging(string value);
    partial void OnFlightNumberChanged();
    partial void OnStopNumChanging(System.Nullable<int> value);
    partial void OnStopNumChanged();
    partial void OnHasDownStopChanging(System.Nullable<bool> value);
    partial void OnHasDownStopChanged();
    partial void OnDurationChanging(System.Nullable<int> value);
    partial void OnDurationChanged();
    partial void OnNoRefundChanging(System.Nullable<bool> value);
    partial void OnNoRefundChanged();
    partial void OnGroupClassChanging(string value);
    partial void OnGroupClassChanged();
    partial void OnFareClassChanging(string value);
    partial void OnFareClassChanged();
    partial void OnFareBasisChanging(string value);
    partial void OnFareBasisChanged();
    partial void OnSeatRemainChanging(System.Nullable<int> value);
    partial void OnSeatRemainChanged();
    partial void OnPromoChanging(System.Nullable<bool> value);
    partial void OnPromoChanged();
    partial void OnFlightValueChanging(string value);
    partial void OnFlightValueChanged();
    #endregion
		
		public tblBookResponseFlight()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookingId", DbType="Int")]
		public System.Nullable<int> BookingId
		{
			get
			{
				return this._BookingId;
			}
			set
			{
				if ((this._BookingId != value))
				{
					this.OnBookingIdChanging(value);
					this.SendPropertyChanging();
					this._BookingId = value;
					this.SendPropertyChanged("BookingId");
					this.OnBookingIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FareDataId", DbType="Int")]
		public System.Nullable<int> FareDataId
		{
			get
			{
				return this._FareDataId;
			}
			set
			{
				if ((this._FareDataId != value))
				{
					this.OnFareDataIdChanging(value);
					this.SendPropertyChanging();
					this._FareDataId = value;
					this.SendPropertyChanged("FareDataId");
					this.OnFareDataIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightId", DbType="Int")]
		public System.Nullable<int> FlightId
		{
			get
			{
				return this._FlightId;
			}
			set
			{
				if ((this._FlightId != value))
				{
					this.OnFlightIdChanging(value);
					this.SendPropertyChanging();
					this._FlightId = value;
					this.SendPropertyChanged("FlightId");
					this.OnFlightIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Leg", DbType="Int")]
		public System.Nullable<int> Leg
		{
			get
			{
				return this._Leg;
			}
			set
			{
				if ((this._Leg != value))
				{
					this.OnLegChanging(value);
					this.SendPropertyChanging();
					this._Leg = value;
					this.SendPropertyChanged("Leg");
					this.OnLegChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Airline", DbType="NVarChar(50)")]
		public string Airline
		{
			get
			{
				return this._Airline;
			}
			set
			{
				if ((this._Airline != value))
				{
					this.OnAirlineChanging(value);
					this.SendPropertyChanging();
					this._Airline = value;
					this.SendPropertyChanged("Airline");
					this.OnAirlineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operating", DbType="NVarChar(500)")]
		public string Operating
		{
			get
			{
				return this._Operating;
			}
			set
			{
				if ((this._Operating != value))
				{
					this.OnOperatingChanging(value);
					this.SendPropertyChanging();
					this._Operating = value;
					this.SendPropertyChanged("Operating");
					this.OnOperatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartPoint", DbType="NVarChar(50)")]
		public string StartPoint
		{
			get
			{
				return this._StartPoint;
			}
			set
			{
				if ((this._StartPoint != value))
				{
					this.OnStartPointChanging(value);
					this.SendPropertyChanging();
					this._StartPoint = value;
					this.SendPropertyChanged("StartPoint");
					this.OnStartPointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndPoint", DbType="NVarChar(50)")]
		public string EndPoint
		{
			get
			{
				return this._EndPoint;
			}
			set
			{
				if ((this._EndPoint != value))
				{
					this.OnEndPointChanging(value);
					this.SendPropertyChanging();
					this._EndPoint = value;
					this.SendPropertyChanged("EndPoint");
					this.OnEndPointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this.OnEndDateChanging(value);
					this.SendPropertyChanging();
					this._EndDate = value;
					this.SendPropertyChanged("EndDate");
					this.OnEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDt", DbType="NVarChar(100)")]
		public string StartDt
		{
			get
			{
				return this._StartDt;
			}
			set
			{
				if ((this._StartDt != value))
				{
					this.OnStartDtChanging(value);
					this.SendPropertyChanging();
					this._StartDt = value;
					this.SendPropertyChanged("StartDt");
					this.OnStartDtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDt", DbType="NVarChar(100)")]
		public string EndDt
		{
			get
			{
				return this._EndDt;
			}
			set
			{
				if ((this._EndDt != value))
				{
					this.OnEndDtChanging(value);
					this.SendPropertyChanging();
					this._EndDt = value;
					this.SendPropertyChanged("EndDt");
					this.OnEndDtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightNumber", DbType="NVarChar(100)")]
		public string FlightNumber
		{
			get
			{
				return this._FlightNumber;
			}
			set
			{
				if ((this._FlightNumber != value))
				{
					this.OnFlightNumberChanging(value);
					this.SendPropertyChanging();
					this._FlightNumber = value;
					this.SendPropertyChanged("FlightNumber");
					this.OnFlightNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StopNum", DbType="Int")]
		public System.Nullable<int> StopNum
		{
			get
			{
				return this._StopNum;
			}
			set
			{
				if ((this._StopNum != value))
				{
					this.OnStopNumChanging(value);
					this.SendPropertyChanging();
					this._StopNum = value;
					this.SendPropertyChanged("StopNum");
					this.OnStopNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasDownStop", DbType="Bit")]
		public System.Nullable<bool> HasDownStop
		{
			get
			{
				return this._HasDownStop;
			}
			set
			{
				if ((this._HasDownStop != value))
				{
					this.OnHasDownStopChanging(value);
					this.SendPropertyChanging();
					this._HasDownStop = value;
					this.SendPropertyChanged("HasDownStop");
					this.OnHasDownStopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duration", DbType="Int")]
		public System.Nullable<int> Duration
		{
			get
			{
				return this._Duration;
			}
			set
			{
				if ((this._Duration != value))
				{
					this.OnDurationChanging(value);
					this.SendPropertyChanging();
					this._Duration = value;
					this.SendPropertyChanged("Duration");
					this.OnDurationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoRefund", DbType="Bit")]
		public System.Nullable<bool> NoRefund
		{
			get
			{
				return this._NoRefund;
			}
			set
			{
				if ((this._NoRefund != value))
				{
					this.OnNoRefundChanging(value);
					this.SendPropertyChanging();
					this._NoRefund = value;
					this.SendPropertyChanged("NoRefund");
					this.OnNoRefundChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupClass", DbType="NVarChar(100)")]
		public string GroupClass
		{
			get
			{
				return this._GroupClass;
			}
			set
			{
				if ((this._GroupClass != value))
				{
					this.OnGroupClassChanging(value);
					this.SendPropertyChanging();
					this._GroupClass = value;
					this.SendPropertyChanged("GroupClass");
					this.OnGroupClassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FareClass", DbType="NVarChar(100)")]
		public string FareClass
		{
			get
			{
				return this._FareClass;
			}
			set
			{
				if ((this._FareClass != value))
				{
					this.OnFareClassChanging(value);
					this.SendPropertyChanging();
					this._FareClass = value;
					this.SendPropertyChanged("FareClass");
					this.OnFareClassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FareBasis", DbType="NVarChar(100)")]
		public string FareBasis
		{
			get
			{
				return this._FareBasis;
			}
			set
			{
				if ((this._FareBasis != value))
				{
					this.OnFareBasisChanging(value);
					this.SendPropertyChanging();
					this._FareBasis = value;
					this.SendPropertyChanged("FareBasis");
					this.OnFareBasisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeatRemain", DbType="Int")]
		public System.Nullable<int> SeatRemain
		{
			get
			{
				return this._SeatRemain;
			}
			set
			{
				if ((this._SeatRemain != value))
				{
					this.OnSeatRemainChanging(value);
					this.SendPropertyChanging();
					this._SeatRemain = value;
					this.SendPropertyChanged("SeatRemain");
					this.OnSeatRemainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Promo", DbType="Bit")]
		public System.Nullable<bool> Promo
		{
			get
			{
				return this._Promo;
			}
			set
			{
				if ((this._Promo != value))
				{
					this.OnPromoChanging(value);
					this.SendPropertyChanging();
					this._Promo = value;
					this.SendPropertyChanged("Promo");
					this.OnPromoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightValue", DbType="NVarChar(1000)")]
		public string FlightValue
		{
			get
			{
				return this._FlightValue;
			}
			set
			{
				if ((this._FlightValue != value))
				{
					this.OnFlightValueChanging(value);
					this.SendPropertyChanging();
					this._FlightValue = value;
					this.SendPropertyChanged("FlightValue");
					this.OnFlightValueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblBookResponseSegment")]
	public partial class tblBookResponseSegment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _SegmentId;
		
		private System.Nullable<int> _FlightId;
		
		private System.Nullable<int> _FareDataId;
		
		private System.Nullable<int> _BookingId;
		
		private string _Airline;
		
		private string _MarketingAirline;
		
		private string _OperatingAirline;
		
		private string _StartPoint;
		
		private string _EndPoint;
		
		private System.Nullable<System.DateTime> _StartTime;
		
		private System.Nullable<System.DateTime> _EndTime;
		
		private string _StartTm;
		
		private string _EndTm;
		
		private string _FlightNumber;
		
		private System.Nullable<int> _Duration;
		
		private string _Class;
		
		private System.Nullable<int> _Seat;
		
		private string _Plane;
		
		private string _StartTerminal;
		
		private string _EndTerminal;
		
		private System.Nullable<bool> _HasStop;
		
		private string _StopPoint;
		
		private System.Nullable<int> _StopTime;
		
		private System.Nullable<bool> _DayChange;
		
		private System.Nullable<bool> _StopOvernight;
		
		private System.Nullable<bool> _ChangeStation;
		
		private System.Nullable<bool> _ChangeAirport;
		
		private System.Nullable<bool> _LastItem;
		
		private string _HandBaggage;
		
		private string _AllowanceBaggage;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSegmentIdChanging(System.Nullable<int> value);
    partial void OnSegmentIdChanged();
    partial void OnFlightIdChanging(System.Nullable<int> value);
    partial void OnFlightIdChanged();
    partial void OnFareDataIdChanging(System.Nullable<int> value);
    partial void OnFareDataIdChanged();
    partial void OnBookingIdChanging(System.Nullable<int> value);
    partial void OnBookingIdChanged();
    partial void OnAirlineChanging(string value);
    partial void OnAirlineChanged();
    partial void OnMarketingAirlineChanging(string value);
    partial void OnMarketingAirlineChanged();
    partial void OnOperatingAirlineChanging(string value);
    partial void OnOperatingAirlineChanged();
    partial void OnStartPointChanging(string value);
    partial void OnStartPointChanged();
    partial void OnEndPointChanging(string value);
    partial void OnEndPointChanged();
    partial void OnStartTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnStartTimeChanged();
    partial void OnEndTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnEndTimeChanged();
    partial void OnStartTmChanging(string value);
    partial void OnStartTmChanged();
    partial void OnEndTmChanging(string value);
    partial void OnEndTmChanged();
    partial void OnFlightNumberChanging(string value);
    partial void OnFlightNumberChanged();
    partial void OnDurationChanging(System.Nullable<int> value);
    partial void OnDurationChanged();
    partial void OnClassChanging(string value);
    partial void OnClassChanged();
    partial void OnSeatChanging(System.Nullable<int> value);
    partial void OnSeatChanged();
    partial void OnPlaneChanging(string value);
    partial void OnPlaneChanged();
    partial void OnStartTerminalChanging(string value);
    partial void OnStartTerminalChanged();
    partial void OnEndTerminalChanging(string value);
    partial void OnEndTerminalChanged();
    partial void OnHasStopChanging(System.Nullable<bool> value);
    partial void OnHasStopChanged();
    partial void OnStopPointChanging(string value);
    partial void OnStopPointChanged();
    partial void OnStopTimeChanging(System.Nullable<int> value);
    partial void OnStopTimeChanged();
    partial void OnDayChangeChanging(System.Nullable<bool> value);
    partial void OnDayChangeChanged();
    partial void OnStopOvernightChanging(System.Nullable<bool> value);
    partial void OnStopOvernightChanged();
    partial void OnChangeStationChanging(System.Nullable<bool> value);
    partial void OnChangeStationChanged();
    partial void OnChangeAirportChanging(System.Nullable<bool> value);
    partial void OnChangeAirportChanged();
    partial void OnLastItemChanging(System.Nullable<bool> value);
    partial void OnLastItemChanged();
    partial void OnHandBaggageChanging(string value);
    partial void OnHandBaggageChanged();
    partial void OnAllowanceBaggageChanging(string value);
    partial void OnAllowanceBaggageChanged();
    #endregion
		
		public tblBookResponseSegment()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegmentId", DbType="Int")]
		public System.Nullable<int> SegmentId
		{
			get
			{
				return this._SegmentId;
			}
			set
			{
				if ((this._SegmentId != value))
				{
					this.OnSegmentIdChanging(value);
					this.SendPropertyChanging();
					this._SegmentId = value;
					this.SendPropertyChanged("SegmentId");
					this.OnSegmentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightId", DbType="Int")]
		public System.Nullable<int> FlightId
		{
			get
			{
				return this._FlightId;
			}
			set
			{
				if ((this._FlightId != value))
				{
					this.OnFlightIdChanging(value);
					this.SendPropertyChanging();
					this._FlightId = value;
					this.SendPropertyChanged("FlightId");
					this.OnFlightIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FareDataId", DbType="Int")]
		public System.Nullable<int> FareDataId
		{
			get
			{
				return this._FareDataId;
			}
			set
			{
				if ((this._FareDataId != value))
				{
					this.OnFareDataIdChanging(value);
					this.SendPropertyChanging();
					this._FareDataId = value;
					this.SendPropertyChanged("FareDataId");
					this.OnFareDataIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookingId", DbType="Int")]
		public System.Nullable<int> BookingId
		{
			get
			{
				return this._BookingId;
			}
			set
			{
				if ((this._BookingId != value))
				{
					this.OnBookingIdChanging(value);
					this.SendPropertyChanging();
					this._BookingId = value;
					this.SendPropertyChanged("BookingId");
					this.OnBookingIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Airline", DbType="NVarChar(50)")]
		public string Airline
		{
			get
			{
				return this._Airline;
			}
			set
			{
				if ((this._Airline != value))
				{
					this.OnAirlineChanging(value);
					this.SendPropertyChanging();
					this._Airline = value;
					this.SendPropertyChanged("Airline");
					this.OnAirlineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarketingAirline", DbType="NVarChar(100)")]
		public string MarketingAirline
		{
			get
			{
				return this._MarketingAirline;
			}
			set
			{
				if ((this._MarketingAirline != value))
				{
					this.OnMarketingAirlineChanging(value);
					this.SendPropertyChanging();
					this._MarketingAirline = value;
					this.SendPropertyChanged("MarketingAirline");
					this.OnMarketingAirlineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatingAirline", DbType="NVarChar(100)")]
		public string OperatingAirline
		{
			get
			{
				return this._OperatingAirline;
			}
			set
			{
				if ((this._OperatingAirline != value))
				{
					this.OnOperatingAirlineChanging(value);
					this.SendPropertyChanging();
					this._OperatingAirline = value;
					this.SendPropertyChanged("OperatingAirline");
					this.OnOperatingAirlineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartPoint", DbType="NVarChar(50)")]
		public string StartPoint
		{
			get
			{
				return this._StartPoint;
			}
			set
			{
				if ((this._StartPoint != value))
				{
					this.OnStartPointChanging(value);
					this.SendPropertyChanging();
					this._StartPoint = value;
					this.SendPropertyChanged("StartPoint");
					this.OnStartPointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndPoint", DbType="NVarChar(50)")]
		public string EndPoint
		{
			get
			{
				return this._EndPoint;
			}
			set
			{
				if ((this._EndPoint != value))
				{
					this.OnEndPointChanging(value);
					this.SendPropertyChanging();
					this._EndPoint = value;
					this.SendPropertyChanged("EndPoint");
					this.OnEndPointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartTime
		{
			get
			{
				return this._StartTime;
			}
			set
			{
				if ((this._StartTime != value))
				{
					this.OnStartTimeChanging(value);
					this.SendPropertyChanging();
					this._StartTime = value;
					this.SendPropertyChanged("StartTime");
					this.OnStartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndTime
		{
			get
			{
				return this._EndTime;
			}
			set
			{
				if ((this._EndTime != value))
				{
					this.OnEndTimeChanging(value);
					this.SendPropertyChanging();
					this._EndTime = value;
					this.SendPropertyChanged("EndTime");
					this.OnEndTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartTm", DbType="NVarChar(100)")]
		public string StartTm
		{
			get
			{
				return this._StartTm;
			}
			set
			{
				if ((this._StartTm != value))
				{
					this.OnStartTmChanging(value);
					this.SendPropertyChanging();
					this._StartTm = value;
					this.SendPropertyChanged("StartTm");
					this.OnStartTmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndTm", DbType="NVarChar(100)")]
		public string EndTm
		{
			get
			{
				return this._EndTm;
			}
			set
			{
				if ((this._EndTm != value))
				{
					this.OnEndTmChanging(value);
					this.SendPropertyChanging();
					this._EndTm = value;
					this.SendPropertyChanged("EndTm");
					this.OnEndTmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightNumber", DbType="NVarChar(100)")]
		public string FlightNumber
		{
			get
			{
				return this._FlightNumber;
			}
			set
			{
				if ((this._FlightNumber != value))
				{
					this.OnFlightNumberChanging(value);
					this.SendPropertyChanging();
					this._FlightNumber = value;
					this.SendPropertyChanged("FlightNumber");
					this.OnFlightNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duration", DbType="Int")]
		public System.Nullable<int> Duration
		{
			get
			{
				return this._Duration;
			}
			set
			{
				if ((this._Duration != value))
				{
					this.OnDurationChanging(value);
					this.SendPropertyChanging();
					this._Duration = value;
					this.SendPropertyChanged("Duration");
					this.OnDurationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Class", DbType="NVarChar(100)")]
		public string Class
		{
			get
			{
				return this._Class;
			}
			set
			{
				if ((this._Class != value))
				{
					this.OnClassChanging(value);
					this.SendPropertyChanging();
					this._Class = value;
					this.SendPropertyChanged("Class");
					this.OnClassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seat", DbType="Int")]
		public System.Nullable<int> Seat
		{
			get
			{
				return this._Seat;
			}
			set
			{
				if ((this._Seat != value))
				{
					this.OnSeatChanging(value);
					this.SendPropertyChanging();
					this._Seat = value;
					this.SendPropertyChanged("Seat");
					this.OnSeatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Plane", DbType="NVarChar(100)")]
		public string Plane
		{
			get
			{
				return this._Plane;
			}
			set
			{
				if ((this._Plane != value))
				{
					this.OnPlaneChanging(value);
					this.SendPropertyChanging();
					this._Plane = value;
					this.SendPropertyChanged("Plane");
					this.OnPlaneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartTerminal", DbType="NVarChar(100)")]
		public string StartTerminal
		{
			get
			{
				return this._StartTerminal;
			}
			set
			{
				if ((this._StartTerminal != value))
				{
					this.OnStartTerminalChanging(value);
					this.SendPropertyChanging();
					this._StartTerminal = value;
					this.SendPropertyChanged("StartTerminal");
					this.OnStartTerminalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndTerminal", DbType="NVarChar(100)")]
		public string EndTerminal
		{
			get
			{
				return this._EndTerminal;
			}
			set
			{
				if ((this._EndTerminal != value))
				{
					this.OnEndTerminalChanging(value);
					this.SendPropertyChanging();
					this._EndTerminal = value;
					this.SendPropertyChanged("EndTerminal");
					this.OnEndTerminalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasStop", DbType="Bit")]
		public System.Nullable<bool> HasStop
		{
			get
			{
				return this._HasStop;
			}
			set
			{
				if ((this._HasStop != value))
				{
					this.OnHasStopChanging(value);
					this.SendPropertyChanging();
					this._HasStop = value;
					this.SendPropertyChanged("HasStop");
					this.OnHasStopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StopPoint", DbType="NVarChar(100)")]
		public string StopPoint
		{
			get
			{
				return this._StopPoint;
			}
			set
			{
				if ((this._StopPoint != value))
				{
					this.OnStopPointChanging(value);
					this.SendPropertyChanging();
					this._StopPoint = value;
					this.SendPropertyChanged("StopPoint");
					this.OnStopPointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StopTime", DbType="Int")]
		public System.Nullable<int> StopTime
		{
			get
			{
				return this._StopTime;
			}
			set
			{
				if ((this._StopTime != value))
				{
					this.OnStopTimeChanging(value);
					this.SendPropertyChanging();
					this._StopTime = value;
					this.SendPropertyChanged("StopTime");
					this.OnStopTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DayChange", DbType="Bit")]
		public System.Nullable<bool> DayChange
		{
			get
			{
				return this._DayChange;
			}
			set
			{
				if ((this._DayChange != value))
				{
					this.OnDayChangeChanging(value);
					this.SendPropertyChanging();
					this._DayChange = value;
					this.SendPropertyChanged("DayChange");
					this.OnDayChangeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StopOvernight", DbType="Bit")]
		public System.Nullable<bool> StopOvernight
		{
			get
			{
				return this._StopOvernight;
			}
			set
			{
				if ((this._StopOvernight != value))
				{
					this.OnStopOvernightChanging(value);
					this.SendPropertyChanging();
					this._StopOvernight = value;
					this.SendPropertyChanged("StopOvernight");
					this.OnStopOvernightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangeStation", DbType="Bit")]
		public System.Nullable<bool> ChangeStation
		{
			get
			{
				return this._ChangeStation;
			}
			set
			{
				if ((this._ChangeStation != value))
				{
					this.OnChangeStationChanging(value);
					this.SendPropertyChanging();
					this._ChangeStation = value;
					this.SendPropertyChanged("ChangeStation");
					this.OnChangeStationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangeAirport", DbType="Bit")]
		public System.Nullable<bool> ChangeAirport
		{
			get
			{
				return this._ChangeAirport;
			}
			set
			{
				if ((this._ChangeAirport != value))
				{
					this.OnChangeAirportChanging(value);
					this.SendPropertyChanging();
					this._ChangeAirport = value;
					this.SendPropertyChanged("ChangeAirport");
					this.OnChangeAirportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastItem", DbType="Bit")]
		public System.Nullable<bool> LastItem
		{
			get
			{
				return this._LastItem;
			}
			set
			{
				if ((this._LastItem != value))
				{
					this.OnLastItemChanging(value);
					this.SendPropertyChanging();
					this._LastItem = value;
					this.SendPropertyChanged("LastItem");
					this.OnLastItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HandBaggage", DbType="NVarChar(1000)")]
		public string HandBaggage
		{
			get
			{
				return this._HandBaggage;
			}
			set
			{
				if ((this._HandBaggage != value))
				{
					this.OnHandBaggageChanging(value);
					this.SendPropertyChanging();
					this._HandBaggage = value;
					this.SendPropertyChanged("HandBaggage");
					this.OnHandBaggageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllowanceBaggage", DbType="NVarChar(1000)")]
		public string AllowanceBaggage
		{
			get
			{
				return this._AllowanceBaggage;
			}
			set
			{
				if ((this._AllowanceBaggage != value))
				{
					this.OnAllowanceBaggageChanging(value);
					this.SendPropertyChanging();
					this._AllowanceBaggage = value;
					this.SendPropertyChanged("AllowanceBaggage");
					this.OnAllowanceBaggageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblBookResponse")]
	public partial class tblBookResponse : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<double> _BookingId;
		
		private System.Nullable<bool> _Status;
		
		private string _ErrorCode;
		
		private string _ErrorValue;
		
		private string _ErrorField;
		
		private string _Message;
		
		private string _Language;
		
		private string _RequestJson;
		
		private string _ResponseJson;
		
		private string _SourceSite;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBookingIdChanging(System.Nullable<double> value);
    partial void OnBookingIdChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    partial void OnErrorCodeChanging(string value);
    partial void OnErrorCodeChanged();
    partial void OnErrorValueChanging(string value);
    partial void OnErrorValueChanged();
    partial void OnErrorFieldChanging(string value);
    partial void OnErrorFieldChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnLanguageChanging(string value);
    partial void OnLanguageChanged();
    partial void OnRequestJsonChanging(string value);
    partial void OnRequestJsonChanged();
    partial void OnResponseJsonChanging(string value);
    partial void OnResponseJsonChanged();
    partial void OnSourceSiteChanging(string value);
    partial void OnSourceSiteChanged();
    #endregion
		
		public tblBookResponse()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookingId", DbType="Float")]
		public System.Nullable<double> BookingId
		{
			get
			{
				return this._BookingId;
			}
			set
			{
				if ((this._BookingId != value))
				{
					this.OnBookingIdChanging(value);
					this.SendPropertyChanging();
					this._BookingId = value;
					this.SendPropertyChanged("BookingId");
					this.OnBookingIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorCode", DbType="NVarChar(MAX)")]
		public string ErrorCode
		{
			get
			{
				return this._ErrorCode;
			}
			set
			{
				if ((this._ErrorCode != value))
				{
					this.OnErrorCodeChanging(value);
					this.SendPropertyChanging();
					this._ErrorCode = value;
					this.SendPropertyChanged("ErrorCode");
					this.OnErrorCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorValue", DbType="NVarChar(MAX)")]
		public string ErrorValue
		{
			get
			{
				return this._ErrorValue;
			}
			set
			{
				if ((this._ErrorValue != value))
				{
					this.OnErrorValueChanging(value);
					this.SendPropertyChanging();
					this._ErrorValue = value;
					this.SendPropertyChanged("ErrorValue");
					this.OnErrorValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorField", DbType="NVarChar(MAX)")]
		public string ErrorField
		{
			get
			{
				return this._ErrorField;
			}
			set
			{
				if ((this._ErrorField != value))
				{
					this.OnErrorFieldChanging(value);
					this.SendPropertyChanging();
					this._ErrorField = value;
					this.SendPropertyChanged("ErrorField");
					this.OnErrorFieldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="NVarChar(MAX)")]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this.OnMessageChanging(value);
					this.SendPropertyChanging();
					this._Message = value;
					this.SendPropertyChanged("Message");
					this.OnMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Language", DbType="NVarChar(MAX)")]
		public string Language
		{
			get
			{
				return this._Language;
			}
			set
			{
				if ((this._Language != value))
				{
					this.OnLanguageChanging(value);
					this.SendPropertyChanging();
					this._Language = value;
					this.SendPropertyChanged("Language");
					this.OnLanguageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestJson", DbType="NVarChar(MAX)")]
		public string RequestJson
		{
			get
			{
				return this._RequestJson;
			}
			set
			{
				if ((this._RequestJson != value))
				{
					this.OnRequestJsonChanging(value);
					this.SendPropertyChanging();
					this._RequestJson = value;
					this.SendPropertyChanged("RequestJson");
					this.OnRequestJsonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResponseJson", DbType="NVarChar(MAX)")]
		public string ResponseJson
		{
			get
			{
				return this._ResponseJson;
			}
			set
			{
				if ((this._ResponseJson != value))
				{
					this.OnResponseJsonChanging(value);
					this.SendPropertyChanging();
					this._ResponseJson = value;
					this.SendPropertyChanged("ResponseJson");
					this.OnResponseJsonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceSite", DbType="NVarChar(MAX)")]
		public string SourceSite
		{
			get
			{
				return this._SourceSite;
			}
			set
			{
				if ((this._SourceSite != value))
				{
					this.OnSourceSiteChanging(value);
					this.SendPropertyChanging();
					this._SourceSite = value;
					this.SendPropertyChanged("SourceSite");
					this.OnSourceSiteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
